blog/urls.py
from django.urls import path
from blog.views import BlogDetailView


app_name = 'blog'

urlpatterns = [
    path('detail_article/<int:pk>', BlogDetailView.as_view(), name='detail_article'),
    ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing_service.urls', namespace='mailing_service')),
    path('profile/', include('custom_user.urls', namespace='custom_user')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

custom_user/urls.py
from django.contrib.auth import views as default_views
from django.urls import path
from custom_user import views as customer_views


app_name = 'custom_user'

urlpatterns = [
    # Вход / Выход из аккаунта
    path('login/', default_views.LoginView.as_view(template_name='custom_user/log_in.html'), name='log_in'),
    path('logout/', default_views.LogoutView.as_view(template_name='custom_user/log_out.html'), name='log_out'),

    # Предварительная регистрация нового пользователя без его активации
    path('registration/', customer_views.UserRegistrationView.as_view(), name='registration'),

    # Активация пользователя после перехода по ссылке из письма
    path('verify/<key>/', customer_views.EmailConfirmView.as_view()),
    path('registration/verify/reg-notification', default_views.TemplateView.as_view(
        template_name='custom_user/reg_notification.html'), name='reg_notification'),
    path('registration/verify/email-confirm', default_views.TemplateView.as_view(
        template_name='custom_user/success_verify.html'), name='success_verify'),
]

mailing_service/urls.py
from django.urls import path
from django.views.generic import TemplateView
from mailing_service import views as custom_views


app_name = 'mailing_service'

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='homepage'),
    path('mailing-menu/', custom_views.MailingMenuView.as_view(), name='mailing_menu'),

    # Ссылки для работы с моделью Customers
    path('mailing-menu/users', custom_views.CustomersListView.as_view(), name='customers_list'),
    path('mailing-menu/users/create', custom_views.CustomerCreateView.as_view(), name='customer_create'),
    path('mailing-menu/users/update/<int:pk>', custom_views.CustomerUpdateView.as_view(), name='customer_update'),
    path('mailing-menu/users/delete/<int:pk>', custom_views.CustomerDeleteView.as_view(), name='customer_delete'),
    path('mailing-menu/users/block-unblock/<int:pk>', custom_views.ToggleAccountStatusView.as_view(), name='toggle_account'),

    # Ссылки для работы с моделью MailingSettings
    path('mailing-settings', custom_views.MailingSettingsListView.as_view(), name='mail_settings_table'),
    path('mailing-settings/create', custom_views.MailingSettingsCreateView.as_view(), name='mail_settings_create'),
    path('mailing-settings/detail/<int:pk>', custom_views.MailingSettingsDetailView.as_view(), name='mail_settings_detail'),
    path('mailing-settings/delete/<int:pk>', custom_views.MailingSettingsDeleteView.as_view(), name='mail_settings_delete'),
    path('mailing-settings/stop-run/<int:pk>', custom_views.ToggleSendingStatusView.as_view(), name='toggle_mail_settings_status'),

    # Ссылка для просмотра логов рассылок
    path('message-logs/', custom_views.MessagesLogsListView.as_view(), name='message_logs'),
]

mailing_service/models/customers.py
from django.contrib.auth import get_user_model
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class Customers(models.Model):

    CUSTOMER_STATUS = [
        (True, 'Активен'),
        (False, 'Заблокирован')
    ]

    email = models.EmailField(verbose_name='Почта', unique=True)
    first_name = models.CharField(max_length=20, verbose_name='Имя')
    surname = models.CharField(max_length=20, verbose_name='Фамилия')
    patronymic = models.CharField(max_length=40, verbose_name='Отчество', **NULLABLE)
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)

    # Атрибут для блокировки пользователя менеджером
    is_active = models.BooleanField(default=True, choices=CUSTOMER_STATUS, verbose_name='Статус пользователя')

    # Атрибут для установления принадлежности сущности (создатель клиента-клиент)
    customer_owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='Создатель клиента')

    def __str__(self):
        return f'{self.email} {self.first_name} {self.surname}'

    class Meta:
        verbose_name = 'Клиент сервиса'
        verbose_name_plural = 'Клиенты сервиса'
        ordering = ('pk',)

        permissions = [
            (
                'block_user', 'Block or unblock customer'
            )
        ]

mailing_service/models/logs.py
from django.db import models
from django.utils import timezone

NULLABLE = {'blank': True, 'null': True}


class MessagesLogs(models.Model):

    ATTEMPT_STATUS_CHOICES = [
        (None, 'Не указано'),
        ('received', 'Получено'),
        ('failed', 'Провалено')
    ]

    mailing_settings = models.ForeignKey('MailingSettings', on_delete=models.CASCADE, verbose_name='Настройки рассылки')

    last_attempt_time = models.DateTimeField(default=timezone.now, verbose_name='Время последней попытки')

    attempt_status = models.CharField(max_length=8, choices=ATTEMPT_STATUS_CHOICES, verbose_name='Статус попытки',
                                      default=None)

    server_response = models.TextField(**NULLABLE, verbose_name='Ответ сервера')

    def __str__(self):
        return f'Статус попытки: {self.attempt_status}'

    class Meta:
        verbose_name = 'Логи рассылки'
        verbose_name_plural = 'Логи рассылок'
        ordering = ('attempt_status',)

mailing_service/models/mailing_settings.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone


class MailingSettings(models.Model):
    STATUS_CHOICES = [
        ('created', 'Создана'),
        ('active', 'Запущена'),
        ('closed', 'Завершена')
    ]

    FREQUENCY_CHOICES = [
        (None, 'Не указано'),
        ('OPD', 'Раз в день'),
        ('OPW', 'Раз в неделю'),
        ('OPM', 'Раз в месяц')
    ]

    customers = models.ManyToManyField('Customers', verbose_name='Клиенты')

    # Атрибуты для настройки рассылки
    send_time = models.DateTimeField(default=timezone.now, verbose_name='Время рассылки')
    # time = ...

    frequency = models.CharField(
        max_length=3, choices=FREQUENCY_CHOICES, default=None, verbose_name='Периодичность'
    )

    sending_status = models.CharField(
        max_length=7, choices=STATUS_CHOICES, default='created', verbose_name='Статус отправки'
    )

    # Атрибуты для создания письма в рассылке
    message_title = models.CharField(max_length=250, verbose_name='Тема письма')
    message_content = models.TextField(verbose_name='Содержание')

    mailing_owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='Создатель рассылки')

    def __str__(self):
        return f'Периодичность: {self.frequency}. Статус отправки: {self.sending_status}'

    class Meta:
        verbose_name = 'Настройка рассылки'
        verbose_name_plural = 'Настройки рассылок'
        ordering = ('pk', 'sending_status')

        permissions = [
            (
                'stop_mailing', 'Stop or run mailing'
            )
        ]

mailing_service/forms.py
from django import forms
from mailing_service.models import Customers, MailingSettings


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class CustomerForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Customers
        exclude = ('is_active', 'customer_owner',)


class MailingSettingsForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = MailingSettings
        exclude = ('sending_status', 'mailing_owner',)

mailing_service/views/customer_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from mailing_service.forms import CustomerForm
from mailing_service.models import Customers


class CustomersListView(generic.ListView):
    model = Customers
    template_name = 'mailing_service/customers_table.html'

    def get_queryset(self):
        # if self.request.user.is_superuser:
        if self.request.user.is_superuser or self.request.user.groups.filter(name='Менеджеры').exists():

            # Если пользователь является суперпользователем, выводим все созданные рассылки
            return self.model.objects.all()

        else:
            # Иначе фильтруем рассылки только по текущему пользователю
            return self.model.objects.filter(customer_owner=self.request.user)


class CustomerCreateView(generic.CreateView):
    form_class = CustomerForm
    template_name = 'mailing_service/customer_creating.html'
    success_url = reverse_lazy('mailing_service:customers_list')

    def form_valid(self, form):
        form.instance.customer_owner = self.request.user
        return super().form_valid(form)


class CustomerUpdateView(generic.UpdateView):

    model = Customers
    form_class = CustomerForm
    template_name = 'mailing_service/customer_creating.html'
    success_url = reverse_lazy('mailing_service:customers_list')

    def get_object(self, queryset=None):

        self.object = super().get_object(queryset)
        if self.object.customer_owner != self.request.user and not self.request.user.is_superuser:
            raise Http404
        return self.object


class CustomerDeleteView(generic.DeleteView):
    model = Customers
    template_name = 'mailing_service/customer_delete.html'
    success_url = reverse_lazy('mailing_service:customers_list')


class ToggleAccountStatusView(PermissionRequiredMixin, generic.View):

    permission_required = 'mailing_service.block_user'

    def get(self, request, pk):
        client = get_object_or_404(Customers, id=pk)

        if client.is_active:
            client.is_active = False
        else:
            client.is_active = True

        client.save()

        return redirect(reverse('mailing_service:customers_list'))

mailing_service/views/log_views.py
from django.views import generic
from mailing_service.models import MessagesLogs


class MessagesLogsListView(generic.ListView):
    model = MessagesLogs
    template_name = 'mailing_service/message_logs.html'

mailing_service/views/mailing_settings_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic
from mailing_service.forms import MailingSettingsForm
from mailing_service.models import MailingSettings, Customers


class MailingMenuView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'mailing_service/mailing_menu.html'


class MailingSettingsListView(generic.ListView):
    model = MailingSettings
    template_name = 'mailing_service/mail_settings_table.html'

    def get_queryset(self):
        if self.request.user.is_superuser or self.request.user.groups.filter(name='Менеджеры').exists():
            # Если пользователь является суперпользователем, выводим все созданные рассылки
            return self.model.objects.all()

        else:
            # Иначе фильтруем рассылки только по текущему пользователю
            return self.model.objects.filter(mailing_owner=self.request.user)


class MailingSettingsCreateView(generic.CreateView):
    form_class = MailingSettingsForm
    template_name = 'mailing_service/mail_settings_create.html'
    success_url = reverse_lazy('mailing_service:mail_settings_table')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)

        if self.request.user.is_superuser:
            # Если клиент является суперпользователем, выводим всех имеющихся пользователей
            form.fields['customers'].queryset = Customers.objects.all()
            return form

        else:
            # Иначе фильтруем пользователей только по текущему клиенту
            form.fields['customers'].queryset = Customers.objects.filter(customer_owner=self.request.user)
            return form

    def form_valid(self, form):
        form.instance.mailing_owner = self.request.user
        return super().form_valid(form)


class MailingSettingsDetailView(generic.DetailView):
    model = MailingSettings
    template_name = 'mailing_service/mail_settings_detail.html'

    def get_object(self, queryset=None):

        self.object = super().get_object(queryset)
        if self.object.mailing_owner != self.request.user and not self.request.user.is_superuser:
            raise Http404
        return self.object


class MailingSettingsDeleteView(generic.DeleteView):
    model = MailingSettings
    template_name = 'mailing_service/mail_settings_delete.html'
    success_url = reverse_lazy('mailing_service:mail_settings_table')


class ToggleSendingStatusView(PermissionRequiredMixin, generic.View):

    permission_required = 'mailing_service.stop_mailing'

    def get(self, request, pk):
        mailing = get_object_or_404(MailingSettings, id=pk)

        if mailing.sending_status in ('created', 'active'):
            mailing.sending_status = 'closed'
        else:
            mailing.sending_status = 'created'

        mailing.save()

        return redirect(reverse('mailing_service:mail_settings_table'))

mailing_service/templates/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'mailing_service:homepage' %}">
        <img src="{% static 'icon/icon.png' %}" alt="Logo" width="30" height="30">

    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'mailing_service:homepage' %}">Домой</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mailing_service:mailing_menu' %}">Рассылка</a>
            </li>
            <li class="nav-item">
                {% if request.user.is_authenticated %}
                <a class="nav-link" href="{% url 'custom_user:log_out' %}">Выйти | {{request.user}}</a>
                {% else %}
                <a class="nav-link" href="{% url 'custom_user:log_in' %}">Войти</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'custom_user:registration' %}">Зарегистрироваться</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

mailing_service/templates/includes/style_settings.html
<style>
        body {
          font-family: Arial, sans-serif;
          background-color: #f1f1f1;
          margin: 0;
        }

        .container {
          max-width: 1200px;
          margin: 0 auto;
          padding: 20px;
        }

        h1 {
          font-size: 24px;
          font-weight: bold;
          margin-bottom: 20px;
        }

        p {
          font-size: 16px;
          line-height: 1.5;
          margin-bottom: 10px;
        }

        /* Стили для навигационного меню */

        .navbar {
          background-color: #333;
          color: #fff;
        }

        .navbar ul {
          list-style-type: none;
          margin: 0;
          padding: 0;
        }

        .navbar li {
          display: inline-block;
          margin-right: 10px;
        }

        .navbar a {
          color: #fff;
          text-decoration: none;
          padding: 10px;
        }

        .navbar a:hover {
          background-color: #555;
        }

        /* Стили для блога */

        .blog {
          background-color: #fff;
          padding: 20px;
          margin-bottom: 20px;
        }

        .blog h2 {
          font-size: 20px;
          font-weight: bold;
          margin-bottom: 10px;
        }

        .blog p {
          margin-bottom: 10px;
        }

        .blog .author {
          font-style: italic;
          color: #888;
        }

        /* Стили для формы рассылки */

        .newsletter-form {
          background-color: #fff;
          padding: 20px;
        }

        .newsletter-form h2 {
          font-size: 20px;
          font-weight: bold;
          margin-bottom: 10px;
        }

        .newsletter-form input[type="text"],
        .newsletter-form input[type="email"] {
          width: 100%;
          padding: 8px;
          margin-bottom: 10px;
          border: 1px solid #ccc;
        }

        .newsletter-form input[type="submit"] {
          background-color: #333;
          color: #fff;
          padding: 10px 20px;
          border: none;
          cursor: pointer;
        }

        .newsletter-form input[type="submit"]:hover {
          background-color: #555;
        }

</style>