blog/urls.py
from django.urls import path
from blog.views import BlogDetailView


app_name = 'blog'

urlpatterns = [
    path('detail_article/<int:pk>', BlogDetailView.as_view(), name='detail_article'),
    ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing_service.urls', namespace='mailing_service')),
    path('profile/', include('custom_user.urls', namespace='custom_user')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing_service/urls.py
from django.urls import path
from django.views.generic import TemplateView
from mailing_service import views as custom_views


app_name = 'mailing_service'

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='homepage'),
    path('mailing-menu/', custom_views.MailingMenuView.as_view(), name='mailing_menu'),

    # Ссылки для работы с моделью Customers
    path('mailing-menu/users', custom_views.CustomersListView.as_view(), name='customers_list'),
    path('mailing-menu/users/create', custom_views.CustomerCreateView.as_view(), name='customer_create'),
    path('mailing-menu/users/update/<int:pk>', custom_views.CustomerUpdateView.as_view(), name='customer_update'),
    path('mailing-menu/users/delete/<int:pk>', custom_views.CustomerDeleteView.as_view(), name='customer_delete'),
    path('mailing-menu/users/block-unblock/<int:pk>', custom_views.ToggleAccountStatusView.as_view(), name='toggle_account'),

    # Ссылки для работы с моделью MailingSettings
    path('mailing-settings', custom_views.MailingSettingsListView.as_view(), name='mail_settings_table'),
    path('mailing-settings/create', custom_views.MailingSettingsCreateView.as_view(), name='mail_settings_create'),
    path('mailing-settings/detail/<int:pk>', custom_views.MailingSettingsDetailView.as_view(), name='mail_settings_detail'),
    path('mailing-settings/delete/<int:pk>', custom_views.MailingSettingsDeleteView.as_view(), name='mail_settings_delete'),
    path('mailing-settings/stop-run/<int:pk>', custom_views.ToggleSendingStatusView.as_view(), name='toggle_mail_settings_status'),

    # Ссылка для просмотра логов рассылок
    path('message-logs/', custom_views.MessagesLogsListView.as_view(), name='message_logs'),
]

mailing_service/models/customers.py
from django.contrib.auth import get_user_model
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class Customers(models.Model):

    CUSTOMER_STATUS = [
        (True, 'Активен'),
        (False, 'Заблокирован')
    ]

    email = models.EmailField(verbose_name='Почта', unique=True)
    first_name = models.CharField(max_length=20, verbose_name='Имя')
    surname = models.CharField(max_length=20, verbose_name='Фамилия')
    patronymic = models.CharField(max_length=40, verbose_name='Отчество', **NULLABLE)
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)

    # Атрибут для блокировки пользователя менеджером
    is_active = models.BooleanField(default=True, choices=CUSTOMER_STATUS, verbose_name='Статус пользователя')

    # Атрибут для установления принадлежности сущности (создатель клиента-клиент)
    customer_owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='Создатель клиента')

    def __str__(self):
        return f'{self.email} {self.first_name} {self.surname}'

    class Meta:
        verbose_name = 'Клиент сервиса'
        verbose_name_plural = 'Клиенты сервиса'
        ordering = ('pk',)

        permissions = [
            (
                'block_user', 'Block or unblock customer'
            )
        ]

mailing_service/models/logs.py
from django.db import models
from django.utils import timezone

NULLABLE = {'blank': True, 'null': True}


class MessagesLogs(models.Model):

    ATTEMPT_STATUS_CHOICES = [
        (None, 'Не указано'),
        ('received', 'Получено'),
        ('failed', 'Провалено')
    ]

    mailing_settings = models.ForeignKey('MailingSettings', on_delete=models.CASCADE, verbose_name='Настройки рассылки')

    last_attempt_time = models.DateTimeField(default=timezone.now, verbose_name='Время последней попытки')

    attempt_status = models.CharField(max_length=8, choices=ATTEMPT_STATUS_CHOICES, verbose_name='Статус попытки',
                                      default=None)

    server_response = models.TextField(**NULLABLE, verbose_name='Ответ сервера')

    def __str__(self):
        return f'Статус попытки: {self.attempt_status}'

    class Meta:
        verbose_name = 'Логи рассылки'
        verbose_name_plural = 'Логи рассылок'
        ordering = ('attempt_status',)

mailing_service/models/mailing_settings.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone


class MailingSettings(models.Model):
    STATUS_CHOICES = [
        ('created', 'Создана'),
        ('active', 'Запущена'),
        ('closed', 'Завершена')
    ]

    FREQUENCY_CHOICES = [
        (None, 'Не указано'),
        ('OPD', 'Раз в день'),
        ('OPW', 'Раз в неделю'),
        ('OPM', 'Раз в месяц')
    ]

    customers = models.ManyToManyField('Customers', verbose_name='Клиенты')

    # Атрибуты для настройки рассылки
    send_time = models.DateTimeField(default=timezone.now, verbose_name='Время рассылки')
    # time = ...

    frequency = models.CharField(
        max_length=3, choices=FREQUENCY_CHOICES, default=None, verbose_name='Периодичность'
    )

    sending_status = models.CharField(
        max_length=7, choices=STATUS_CHOICES, default='created', verbose_name='Статус отправки'
    )

    # Атрибуты для создания письма в рассылке
    message_title = models.CharField(max_length=250, verbose_name='Тема письма')
    message_content = models.TextField(verbose_name='Содержание')

    mailing_owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='Создатель рассылки')

    def __str__(self):
        return f'Периодичность: {self.frequency}. Статус отправки: {self.sending_status}'

    class Meta:
        verbose_name = 'Настройка рассылки'
        verbose_name_plural = 'Настройки рассылок'
        ordering = ('pk', 'sending_status')

        permissions = [
            (
                'stop_mailing', 'Stop or run mailing'
            )
        ]

mailing_service/forms.py
from django import forms
from mailing_service.models import Customers, MailingSettings


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class CustomerForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Customers
        exclude = ('is_active', 'customer_owner',)


class MailingSettingsForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = MailingSettings
        exclude = ('sending_status', 'mailing_owner',)

mailing_service/views/customer_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from mailing_service.forms import CustomerForm
from mailing_service.models import Customers


class CustomersListView(generic.ListView):
    model = Customers
    template_name = 'mailing_service/customers_table.html'

    def get_queryset(self):
        # if self.request.user.is_superuser:
        if self.request.user.is_superuser or self.request.user.groups.filter(name='Менеджеры').exists():

            # Если пользователь является суперпользователем, выводим все созданные рассылки
            return self.model.objects.all()

        else:
            # Иначе фильтруем рассылки только по текущему пользователю
            return self.model.objects.filter(customer_owner=self.request.user)


class CustomerCreateView(generic.CreateView):
    form_class = CustomerForm
    template_name = 'mailing_service/customer_creating.html'
    success_url = reverse_lazy('mailing_service:customers_list')

    def form_valid(self, form):
        form.instance.customer_owner = self.request.user
        return super().form_valid(form)


class CustomerUpdateView(generic.UpdateView):

    model = Customers
    form_class = CustomerForm
    template_name = 'mailing_service/customer_creating.html'
    success_url = reverse_lazy('mailing_service:customers_list')

    def get_object(self, queryset=None):

        self.object = super().get_object(queryset)
        if self.object.customer_owner != self.request.user and not self.request.user.is_superuser:
            raise Http404
        return self.object


class CustomerDeleteView(generic.DeleteView):
    model = Customers
    template_name = 'mailing_service/customer_delete.html'
    success_url = reverse_lazy('mailing_service:customers_list')


class ToggleAccountStatusView(PermissionRequiredMixin, generic.View):

    permission_required = 'mailing_service.block_user'

    def get(self, request, pk):
        client = get_object_or_404(Customers, id=pk)

        if client.is_active:
            client.is_active = False
        else:
            client.is_active = True

        client.save()

        return redirect(reverse('mailing_service:customers_list'))

mailing_service/views/log_views.py
from django.views import generic
from mailing_service.models import MessagesLogs


class MessagesLogsListView(generic.ListView):
    model = MessagesLogs
    template_name = 'mailing_service/message_logs.html'

mailing_service/views/mailing_settings_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic
from mailing_service.forms import MailingSettingsForm
from mailing_service.models import MailingSettings, Customers


class MailingMenuView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'mailing_service/mailing_menu.html'


class MailingSettingsListView(generic.ListView):
    model = MailingSettings
    template_name = 'mailing_service/mail_settings_table.html'

    def get_queryset(self):
        if self.request.user.is_superuser or self.request.user.groups.filter(name='Менеджеры').exists():
            # Если пользователь является суперпользователем, выводим все созданные рассылки
            return self.model.objects.all()

        else:
            # Иначе фильтруем рассылки только по текущему пользователю
            return self.model.objects.filter(mailing_owner=self.request.user)


class MailingSettingsCreateView(generic.CreateView):
    form_class = MailingSettingsForm
    template_name = 'mailing_service/mail_settings_create.html'
    success_url = reverse_lazy('mailing_service:mail_settings_table')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)

        if self.request.user.is_superuser:
            # Если клиент является суперпользователем, выводим всех имеющихся пользователей
            form.fields['customers'].queryset = Customers.objects.all()
            return form

        else:
            # Иначе фильтруем пользователей только по текущему клиенту
            form.fields['customers'].queryset = Customers.objects.filter(customer_owner=self.request.user)
            return form

    def form_valid(self, form):
        form.instance.mailing_owner = self.request.user
        return super().form_valid(form)


class MailingSettingsDetailView(generic.DetailView):
    model = MailingSettings
    template_name = 'mailing_service/mail_settings_detail.html'

    def get_object(self, queryset=None):

        self.object = super().get_object(queryset)
        if self.object.mailing_owner != self.request.user and not self.request.user.is_superuser:
            raise Http404
        return self.object


class MailingSettingsDeleteView(generic.DeleteView):
    model = MailingSettings
    template_name = 'mailing_service/mail_settings_delete.html'
    success_url = reverse_lazy('mailing_service:mail_settings_table')


class ToggleSendingStatusView(PermissionRequiredMixin, generic.View):

    permission_required = 'mailing_service.stop_mailing'

    def get(self, request, pk):
        mailing = get_object_or_404(MailingSettings, id=pk)

        if mailing.sending_status in ('created', 'active'):
            mailing.sending_status = 'closed'
        else:
            mailing.sending_status = 'created'

        mailing.save()

        return redirect(reverse('mailing_service:mail_settings_table'))

mailing_service/templates/mailing_service/confirm_delete.html
{% extends 'base.html' %}
{% block title %}
Удаление клиента
{% endblock %}
{% block content %}
<div class="container mt-4">
    <div class="col-md-6 offset-md-3">

        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}

            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">Удаление клиента</h2>

                    <p class="card-text">
                        Пожалуйста, подтвердите запрос на удаление клиента.<br>
                        Почта: {{ object.email}}<br>
                        Имя: {{ object.first_name}} | Фамилия: {{ object.surname}}
                    </p>

                    <button type="submit" class="btn btn-outline-success">Удалить</button>
                    <a href="{% url 'mailing_service:customers_list' %}" class="btn btn-outline-warning">Отмена</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

mailing_service/templates/mailing_service/customer_creating.html
{% extends 'base.html' %}
{% block title %}
    {% if object %}
    Изменить клиента
    {% else %}
    Добавить клиента
    {% endif %}
{% endblock %}
{% block content %}
<div class="container mt-4">
    <div class="col-md-6 offset-md-3">

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success btn-sm">
                {% if object %}
                Сохранить изменения
                {% else %}
                Создать клиента
                {% endif %}
            </button>
            <a href="{% url 'mailing_service:mailing_menu' %}" class="btn btn-primary btn-sm">Отмена</a>
        </form>

    </div>
</div>
{% endblock %}

mailing_service/templates/mailing_service/customer_delete.html
{% extends 'base.html' %}
{% block title %}
Удаление клиента
{% endblock %}
{% block content %}
<div class="container mt-4">
    <div class="col-md-6 offset-md-3">

        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}

            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">Удаление клиента</h2>

                    <p class="card-text">
                        Пожалуйста, подтвердите запрос на удаление клиента.<br>
                        Почта: {{ object.email}}<br>
                        Имя: {{ object.first_name}} | Фамилия: {{ object.surname}}
                    </p>

                    <button type="submit" class="btn btn-danger btn-sm">Удалить</button>
                    <a href="{% url 'mailing_service:customers_list' %}" class="btn btn-primary btn-sm">Отмена</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

mailing_service/templates/mailing_service/customers_table.html
{% extends 'base.html' %}
{% block title %}
Все пользователи
{% endblock %}
{% block content %}
{% for object in object_list %}
<div class="container mt-4">

    <table class="table">

        <thead>
        <tr>
            <th>id</th>
            <th>Почта</th>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Редактировать</th>
            <th>Удалить</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row">{{ object.pk }}</th>
            <td>{{ object.email }}</td>
            <td>{{ object.first_name }}</td>
            <td>{{ object.surname }}</td>

            <td><p><a href="{% url 'mailing_service:customer_update' object.pk %}" class="btn btn-primary btn-sm ">Редактировать</a>
            </p>

                {% if perms.mailing_service.block_user or user.is_superuser %}

                    {% if object.is_active %}
                        <a href="{% url 'mailing_service:toggle_account' object.pk %}" class="btn btn-danger btn-sm">Заблокировать</a>
                    {% else %}
                        <a href="{% url 'mailing_service:toggle_account' object.pk %}" class="btn btn-success btn-sm">Активировать</a>
                    </td>
                    {% endif %}

                {% endif %}

            <td><a href="{% url 'mailing_service:customer_delete' object.pk %}"
                   class="btn btn-danger btn-sm">Удалить</a></td>
        </tr>
        </tbody>
    </table>
</div>
{% endfor %}
{% if not object_list %}
<div class="container mt-4">
    <div class="col-md-6 offset-md-3">

        <div class="card">
            <div class="card-body">
                <h2 class="card-title">Информация о клиентах</h2>

                <p class="card-text">
                    В данный момент зарегистрированных пользователей не существует
                </p>
                <a href="{% url 'mailing_service:customer_create' %}" class="btn btn-primary btn-sm">Создать
                    рассылку</a>
                <a href="{% url 'mailing_service:mailing_menu' %}" class="btn btn-primary btn-sm">Назад</a>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

mailing_service/templates/mailing_service/mail_settings_create.html
{% extends 'base.html' %}
{% block title %}
Создать рассылку
{% endblock %}
{% block content %}
<div class="container mt-4">
    <div class="col-md-6 offset-md-3">

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-outline-success">Создать рассылку</button>
            <a href="{% url 'mailing_service:mail_settings_table' %}" class="btn btn-outline-warning">Отмена</a>
        </form>

    </div>
</div>
{% endblock %}

mailing_service/templates/mailing_service/mail_settings_delete.html
{% extends 'base.html' %}
{% block title %}
Удаление рассылки
{% endblock %}
{% block content %}
<div class="container mt-4">
    <div class="col-md-6 offset-md-3">

        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}

            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">Удаление рассылки</h2>

                    <p class="card-text">
                        Пожалуйста, подтвердите запрос на удаление рассылки.
                    </p>

                    <button type="submit" class="btn btn-danger btn-sm">Удалить</button>
                    <a href="{% url 'mailing_service:mail_settings_table' %}" class="btn btn-primary btn-sm">Отмена</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

mailing_service/templates/mailing_service/mail_settings_detail.html
{% extends 'base.html' %}

{% block title %}
Информация о рассылке
{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">Детальная информация о рассылке</h2>

                    <p class="card-text">Получатели:</p>
                    <ul class="list-group">
                        {% for customer in object.customers.all %}
                        <li class="list-group-item">{{ customer.email }} ({{customer.first_name}}
                            {{customer.surname}})
                        </li>
                        {% endfor %}
                    </ul>

                    <br>

                    <p class="card-text">Время отправки:</p>
                    <ul class="list-group">
                        <li class="list-group-item">{{ object.send_time }}</li>
                    </ul>

                    <br>

                    <p class="card-text">Периодичность отправки сообщений:</p>
                    <ul class="list-group">
                        <li class="list-group-item">{{ object.frequency }}</li>
                    </ul>

                    <br>

                    <p class="card-text">Статус отправки:</p>
                    <ul class="list-group">
                        <li class="list-group-item">{{ object.sending_status }}</li>
                    </ul>

                    <br>

                    <p class="card-text">Создатель рассылки:</p>
                    <ul class="list-group">
                        <li class="list-group-item">{{ object.mailing_owner }}</li>
                    </ul>

                    <br>

                    <p class="card-text">Содержание сообщения для рассылки:</p>
                    <ul class="list-group">
                        <li class="list-group-item">Тема сообщения: {{ object.message_title }}</li>
                        <li class="list-group-item">Содержание сообщения: {{ object.message_content }}</li>
                    </ul>
                </div>

                <div class="card-body">
                    <a href="{% url 'mailing_service:mail_settings_table' %}" class="btn btn-primary btn-sm">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing_service/templates/mailing_service/mail_settings_table.html
{% extends 'base.html' %}
{% block title %}
Все рассылки
{% endblock %}
{% block content %}
{% for object in object_list %}
    <div class="container mt-4">
        <table class="table">
            <thead>
            <tr>
                <th>id</th>
                <th>Получатели</th>
                <th>Время рассылки</th>
                <th>Периодичность</th>
                <th>Статус отправки</th>
                <th>Подробнее</th>
                <th>Удалить</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row">{{ object.pk }}</th>
                <td>
                    {% for customer in object.customers.all %}
                    {{ customer.email }} ({{customer.first_name}})<br>
                    {% endfor %}
                </td>
                <td>{{ object.send_time }}</td>
                <td>{{ object.frequency }}</td>
                <td>
                    <p>{{ object.sending_status }}</p>
                    {% if object.sending_status == 'created' or object.sending_status == 'active' %}
                        <a href="{% url 'mailing_service:toggle_mail_settings_status' object.pk %}"
                           class="btn btn-danger btn-sm">Отключить</a>
                    {% else %}
                        <a href="{% url 'mailing_service:toggle_mail_settings_status' object.pk %}"
                           class="btn btn-success btn-sm">Запустить</a>
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'mailing_service:mail_settings_detail' object.pk %}" class="btn btn-primary btn-sm">Подробнее</a>
                </td>
                <td>
                    <a href="{% url 'mailing_service:mail_settings_delete' object.pk %}" class="btn btn-danger btn-sm">Удалить</a>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
{% endfor %}

{% if not object_list %}
    <div class="container mt-4">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">Информация о выполненных рассылках</h2>
                    <p class="card-text">
                        В данный момент выполненных рассылок не обнаружено.
                    </p>
                    <a href="{% url 'mailing_service:mail_settings_create' %}" class="btn btn-primary btn-sm">Создать
                        рассылку</a>
                    <a href="{% url 'mailing_service:mailing_menu' %}" class="btn btn-primary btn-sm">Назад</a>
                </div>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

mailing_service/templates/mailing_service/mailing_menu.html
{% extends 'base.html' %}
{% block title %}
Рассылка
{% endblock %}
{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">Наши пользователи</h2>
                    <p class="card-text">
                        Управление пользователями.</p>
                    <a href="{% url 'mailing_service:customers_list' %}" class="btn btn-primary btn-sm">Показать всех</a>
                    <a href="{% url 'mailing_service:customer_create' %}" class="btn btn-primary btn-sm">Добавить пользователя</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container mt-4">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">Настройка рассылок</h2>
                    <p class="card-text">
                        Создайте новые настройки для рассылки.</p>
                    <a href="{% url 'mailing_service:mail_settings_table' %}" class="btn btn-primary btn-sm">Список рассылок</a>
                    <a href="{% url 'mailing_service:mail_settings_create' %}" class="btn btn-primary btn-sm">Создать рассылку</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container mt-4">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">Информация о статусе рассылок</h2>
                    <p class="card-text">
                        Узнайте статус выполнения ранее запущенных рассылок.</p>
                    <a href="{% url 'mailing_service:message_logs' %}" class="btn btn-primary btn-sm">Узнать статус</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing_service/templates/mailing_service/message_logs.html
{% extends 'base.html' %}
{% block title %}
Логи рассылок
{% endblock %}
{% block content %}
{% for object in object_list %}
<div class="container mt-4">

    <table class="table">

        <thead>
        <tr>
            <th>id</th>
            <th>Настройки рассылки</th>
            <th>Время последней попытки</th>
            <th>Статус попытки</th>
            <th>Ответ сервера</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row">{{ object.pk }}</th>
            <td>{{ object.mailing_settings }}</td>
            <td>{{ object.last_attempt_time }}</td>
            <td>{{ object.attempt_status }}</td>
            <td>{{ object.server_response }}</td>
            </td>
        </tr>
        </tbody>
    </table>
</div>
{% endfor %}
{% if not object_list %}
<div class="container mt-4">
    <div class="col-md-6 offset-md-3">

        <div class="card">
            <div class="card-body">
                <h2 class="card-title">Журнал информации о рассылках</h2>

                <p class="card-text">
                    В данный момент в журнале информации о рассылках нет ни одной записи
                </p>

                <a href="{% url 'mailing_service:mailing_menu' %}" class="btn btn-outline-primary">Назад</a>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}